printWidth: 150
trailingComma: 'all'
tabWidth: 2
semi: false
singleQuote: true
bracketSpacing: true
quoteProps: consistent
arrowParens: always
endOfLine: 'lf'
overrides:
  - files: ['*.ts']
    options:
      parser: typescript
  - files: ['*.html']
    options:
      parser: angular
      printWidth: 200
  - files: ['*.scss']
    options:
      parser: scss
      printWidth: 200
  - files: ['*.json']
    options:
      parser: json
      useTabs: false
  - files: ['*.yml', '*.yaml']
    options:
      parser: yaml
  - files: ['*.md']
    options:
      parser: markdown
      proseWrap: preserve
